addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database dummy_test' -U postgres
language: ruby
rvm:
  - 2.3.0
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake spec
